### ISSUE TITLE
Send email when create a notification

### ISSUE THREAD

**Issue by RafaelMCarvalho** [algorich/notifly#21]
Just it: create a method to send the notifications as email when created. 

We may use the same `template` param to render mailer view. Additionally, we'll need new params:
- `mail`: A flag to send email or not. The options may be `:only`, `true` and `false`. Default is `false`
- `sender_email`: By default it's defined at initializer configurations, but may be override by this param value
- `reply_to`: By default it's defined at initializer configurations, but may be override by this param value

For subject, we will use `I18n` for each template. So, you have to define your locale file like this:

``` yml
en:
  notifly:
    mail_subject:
      default: 'You have a new notification'
      custom_template: 'Custom template subject'
```

The receiver of emails will be always `receiver#email`.
